# Generated by Django 5.2 on 2025-08-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=55, unique=True)),
                ("description", models.TextField(max_length=255)),
                ("poster", models.URLField()),
                ("director", models.CharField(max_length=55)),
                ("cast", models.CharField(max_length=255)),
                ("release", models.DateField()),
                ("duration", models.DurationField()),
                (
                    "parental_guide",
                    models.CharField(
                        choices=[
                            ("general", "G - General Audiences"),
                            ("parental guidance", "PG - Parental Guidance Suggested"),
                            ("parental strongly", "PG-13 - Parents Strongly Cautioned"),
                            ("restricted", "R - Restricted"),
                            ("adults", "NC-17 - Adults Only"),
                        ],
                        default="general",
                        max_length=55,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("french", "French"),
                            ("spanish", "Spanish"),
                            ("german", "German"),
                            ("italian", "Italian"),
                        ],
                        default="english",
                        max_length=55,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genres",
                    models.ManyToManyField(related_name="movies", to="movies.genre"),
                ),
            ],
            options={
                "verbose_name_plural": "Movies",
                "ordering": ["-id"],
            },
        ),
    ]
