# Generated by Django 5.2 on 2025-06-13 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"], "verbose_name_plural": "Genres"},
        ),
    ]
