# Generated by Django 5.2 on 2025-08-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'MasterCard')], max_length=55)),
                ('status', models.CharField(choices=[('declined', 'Declined'), ('accepted', 'Accepted')], max_length=55)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('pending_payment', 'Pending Payment'), ('failed_payment', 'Failed Payment'), ('purchased', 'Purchased')], default='reserved', max_length=55)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.showtime')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['-id'],
            },
        ),
    ]
