# Generated by Django 5.2 on 2025-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-id"], "verbose_name_plural": "Bookings"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-id"], "verbose_name_plural": "Payments"},
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("pending_payment", "Pending Payment"),
                    ("failed_payment", "Failed Payment"),
                    ("purchased", "Purchased"),
                ],
                default="reserved",
                max_length=55,
            ),
        ),
    ]
