# Generated by Django 5.2 on 2025-07-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_booking_options_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("canceled", "Canceled"),
                    ("pending_payment", "Pending Payment"),
                    ("failed_payment", "Failed Payment"),
                    ("purchased", "Purchased"),
                ],
                default="reserved",
                max_length=55,
            ),
        ),
    ]
