# Generated by Django 5.2 on 2025-07-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='bookings',
            field=models.ManyToManyField(related_name='payments', to='tickets.booking'),
        ),
    ]
