# Generated by Django 5.2 on 2025-06-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
