# Generated by Django 5.2 on 2025-06-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("movies", "0002_alter_genre_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=35)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.theater",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Showtimes",
                "ordering": ["movie", "theater__city__name", "date", "time"],
            },
        ),
    ]
