# Generated by Django 5.2 on 2025-07-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_theater_name'),
        ('showtimes', '0002_alter_showtime_options_remove_showtime_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('theater', 'starts_at')},
        ),
    ]
