# Generated by Django 5.2 on 2025-08-11 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"], "verbose_name_plural": "Users"},
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
